# Generated by Django 4.0 on 2022-07-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0001_initial'),
        ('books', '0002_remove_book_content_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='variations',
            field=models.ManyToManyField(related_name='variations', to='variations.Variation'),
        ),
    ]
