# Generated by Django 4.0 on 2022-07-12 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_variations'),
        ('variations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='books.book'),
        ),
    ]
